files:
  - source: CrowdIInTestOverTheAirTranslation/CrowdIInTestOverTheAirTranslation/Localizable.strings
    translation: CrowdIInTestOverTheAirTranslation/CrowdIInTestOverTheAirTranslation/%osx_locale%.lproj/%original_file_name%
