files:
  - source: CrowdIInTestOverTheAirTranslation/CrowdIInTestOverTheAirTranslation/en.lproj/*
    translation: CrowdIInTestOverTheAirTranslation/CrowdIInTestOverTheAirTranslation/%osx_locale%.lproj/%original_file_name%
